# Generated by the PackScript compiler

execute unless block ^ ^ ^1 air if entity @e[distance=0..0.8] run function #tele_wand:tp_ray_hit
execute if block ~ ~ ~ air unless entity @e[distance=0..0.8] positioned ^ ^ ^1 run function packscript:raycast/tp_ray
particle dust 0.788 0.102 0.769 1 ~ ~ ~ 0 0 0 1 0 normal